services:

  postgres:
    image: postgres:17-alpine
    container_name: contextops-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: contextops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: genai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contextops"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - contextops-network


  redis:
    image: redis:8-alpine
    container_name: contextops-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - contextops-network


  qdrant-node-1:
    image: qdrant/qdrant:v1.19.0
    container_name: contextops-qdrant-node-1
    restart: unless-stopped

    environment:
      QDRANT__CLUSTER__ENABLED: "true"

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_node_1_storage:/qdrant/storage

    networks:
      - contextops-network


  qdrant-node-2:
    image: qdrant/qdrant:v1.19.0
    container_name: contextops-qdrant-node-2
    restart: unless-stopped

    environment:
      QDRANT__CLUSTER__ENABLED: "true"

    ports:
      - "6433:6333"
      - "6434:6334"

    volumes:
      - qdrant_node_2_storage:/qdrant/storage

    networks:
      - contextops-network


  qdrant-node-3:
    image: qdrant/qdrant:v1.19.0
    container_name: contextops-qdrant-node-3
    restart: unless-stopped

    environment:
      QDRANT__CLUSTER__ENABLED: "true"

    ports:
      - "6533:6333"
      - "6534:6334"

    volumes:
      - qdrant_node_3_storage:/qdrant/storage

    networks:
      - contextops-network


  contextops:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: contextops-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:genai@postgres:5432/contextops

      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_TTL_SECONDS: "300"
      REDIS_CACHE_KEY_PREFIX: contextops:cache:

      QDRANT_URL: http://qdrant-node-1:6333

      FASTEMBED_CACHE_DIR: /app/.cache/fastembed

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

      qdrant-node-1:
        condition: service_started

      qdrant-node-2:
        condition: service_started

      qdrant-node-3:
        condition: service_started

    volumes:
      - fastembed_cache:/app/.cache/fastembed

    networks:
      - contextops-network


volumes:
  postgres_data:
  redis_data:
  qdrant_node_1_storage:
  qdrant_node_2_storage:
  qdrant_node_3_storage:
  fastembed_cache:


networks:
  contextops-network:
    driver: bridge