from dataclasses import dataclass

from app.domain.document_chunk import DocumentChunk
from app.domain.sparse_embedding import SparseEmbedding


@dataclass
class EmbeddedDocumentChunk:
    """
    A DocumentChunk together with its generated dense and
    sparse embedding representations.
    """

    # Original retrieval-ready document chunk.
    chunk: DocumentChunk

    # Dense semantic embedding generated by the dense
    # EmbeddingProvider.
    vector: list[float]

    # Sparse lexical/BM25 representation generated by the
    # SparseEmbeddingProvider.
    sparse_vector: SparseEmbedding